// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "3b051dd0-1c36-4956-a561-10a02573275c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575381485);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575381605);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575426087);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575426327);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575426207);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575381365);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575381845);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575381725);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 808960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575375099);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f0954d49-698c-4c0f-bbd4-30b5da01d0a5}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575360000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575426116331");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575427909331");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575426066631");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575429666631");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215002044");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575380978");
user_pref("browser.slowStartup.averageTime", 5195);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215002044");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575375106452");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "c1cbddbea6b343c184b201dec8766beb");
user_pref("extensions.blocklist.lastModified", "Tue, 03 Dec 2019 12:46:24 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575381487);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215002044");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"eaacec2e-9dbb-4797-8b35-fe3247494911\",\"screenshots@mozilla.org\":\"8afdd928-9888-4db9-a4bf-c089bf86cb00\",\"webcompat-reporter@mozilla.org\":\"11822a37-1a6f-49ce-a6ae-6886cd507902\",\"webcompat@mozilla.org\":\"3f56b72c-3636-43a2-9ec8-5223816788c6\"}");
user_pref("idle.lastDailyNotification", 1575382471);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575381153);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215002044");
user_pref("media.gmp-manager.lastCheck", 1575381151);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575382471);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "73c4a193-3ea1-46e7-a5cb-423965260750");
user_pref("security.sandbox.plugin.tempDirSuffix", "592734d0-459d-40e5-9f14-5d4befe76242");
user_pref("services.blocklist.addons.checked", 1575381177);
user_pref("services.blocklist.gfx.checked", 1575381177);
user_pref("services.blocklist.onecrl.checked", 1575381177);
user_pref("services.blocklist.pinning.checked", 1575381177);
user_pref("services.blocklist.plugins.checked", 1575381177);
user_pref("services.settings.clock_skew_seconds", -254);
user_pref("services.settings.last_update_seconds", 1575381619);
user_pref("services.settings.main.language-dictionaries.last_check", 1575381177);
user_pref("services.settings.main.sites-classification.last_check", 1575381177);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575382471);
user_pref("toolkit.startup.last_success", 1575380972);
user_pref("toolkit.telemetry.cachedClientID", "c137b067-111c-4a64-a2fe-8bfb81095b7c");
user_pref("toolkit.telemetry.previousBuildID", "20190215002044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
